### ISSUE TITLE
3.4.2 - Confirm Mixin - add width to available parameters when useDefaultConfirm=false

### ISSUE THREAD

**Issue by danowar2k** [got5/tapestry5-jquery#352]
You can set the height of the dialog, but you can't set the width. My confirm box is always too small.

**Comment by got5** [comment]
Hello and welcome to github.

Could you propose a sample based on https://github.com/got5/tapestry5-jquery/blob/maint-3.4.x/src/test/java/org/got5/tapestry5/jquery/pages/JQueryConfirm.java that reproduce you problem?

**Comment by danowar2k** [comment]
What do you need me to do? The documentation says "width" is not among the accepted parameters. I know that the JQuery Dialog component allows "width". The Confirm mixin uses the JQuery Dialog is "useDefaultConfirm" is set to false.
Should I post example code where I try to set "width", so that it can be autotested?

**Comment by danowar2k** [comment]
Pasted from the 
https://github.com/got5/tapestry5-jquery/blob/maint-3.4.x/src/main/java/org/got5/tapestry5/jquery/mixins/Confirm.java

 @AfterRender
public void afterRender()
{
JSONObject config = new JSONObject();
String clientId = element.getClientId();
config.put("id", clientId);
config.put("title", title != null ? title : messageProvider.get("default-confirm-title", clientId, resources));
config.put("message", message != null ? message : messageProvider.get("default-confirm-message", clientId, resources));
config.put("validationMsg", validationMsg != null ? validationMsg : messageProvider.get("default-valid-label", clientId, resources));
config.put("cancelMsg", cancelMsg != null ? cancelMsg : messageProvider.get("default-cancel-label", clientId, resources));
config.put("useDefaultConfirm", useDefaultConfirm);
config.put("isModal", isModal);
config.put("isResizable", isResizable);
config.put("isDraggable", isDraggable);
config.put("height", height);
javaScriptSupport.addInitializerCall(InitializationPriority.EARLY,"confirm", config);
}

No setting of "width" in there.

**Comment by got5** [comment]
In order to give some help for fixing an issue, some people send a pull request to propose a fix.
see https://github.com/blog/1943-how-to-write-the-perfect-pull-request for more details.

If you don't feel confident enough to make a pull request. You can also share some code to show how your are using a component. The best would be to provide simple code that can be reused inside the test page during the test phase. 

This JQueryConfirm.java and the related https://github.com/got5/tapestry5-jquery/blob/maint-3.4.x/src/test/resources/org/got5/tapestry5/jquery/pages/JQueryConfirm.tml are the two parts of the test page.

**Comment by danowar2k** [comment]
I've cloned the repository, created a local branch for the issue and committed my proposed changes to my local clone. Any pointers how I issue a pull request now? Or do I have to fork the repo instead of cloning it?

**Comment by ffacon** [comment]
Providing a Sample
