### ISSUE TITLE
Support of Tapestry 5.4?

### ISSUE THREAD

**Issue by thackel** [got5/tapestry5-jquery#382]
T5-JQuery had its last commit to the 4.1.x branch about half a year ago with about 500 commits behind and the current master is 3.8 for T-5.3.x.

Especially i am looking for the replacement for the T5.* javascript functions of which some have been implemented in the 3.8 branch.

`T5.ajaxRequest`
and

`T5.loadScriptsInReply`

are the missing functions of which at least `tapestry.util.ajaxRequest` is available in 3.8 (but not in 4.1).

**Comment by criedel** [comment]
I think the last maintenance release for T5.3 was 3.5.2. The T5 namespace actually is deprecated since Tapestry 5.4. If you are using T5.4 you should be able to replace `tapestry.util.ajaxRequest`with either `t5/core/dom`'s [ajaxRequest](http://tapestry.apache.org/current/coffeescript/t5-core-dom-jquery.html) or you use `t5/core/ajax`.
I’m not quite sure if `t5/core/ajax` is a public module or an internal one since there’s little to no documentation on tapestry.apache.org.

Do you need a compatibility version of `tapestry.util.ajaxRequest` for upgrading or would replacing ajax references work for you?

**Comment by thackel** [comment]
Thanks for the reply and sorry for my late reaction.
We've finally found a solution with the standard ajax request method and could switch to T5.4.
